// <auto-generated />
namespace BootCampApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddInstructorOfficeAssigment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddInstructorOfficeAssigment));
        
        string IMigrationMetadata.Id
        {
            get { return "201810161744095_AddInstructorOfficeAssigment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
